// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Timestamp struct {
	ID        int64
	Name      string
	Seconds   int64
	Timestamp time.Time
}
